library(dplyr)
my_join<-function(dmc_file){
	dmc<-read.table(paste0("metilene_DMC/",dmc_file),header=F)
	input<-read.table("metilene_mock_treat.input",header=T)
	filter<-semi_join(input, dmc, by=c("chrom"="V1","pos"="V3"))
	write.table(filter,file=paste0("metilene_DMC_input/",dmc_file,".input"),row.names=F,col.names=T,quote=F,sep="\t")
	}

#my_join("metilene_DMC_Col-0")
#my_join("metilene_DMC_ddm1")
#my_join("metilene_DMC_ibm1-1")
#my_join("metilene_DMC_mock_Col-0_ddm1")
#my_join("metilene_DMC_mock_Col-0_ibm1-1")
#my_join("metilene_DMC_mock_Col-0_rdd2")
#my_join("metilene_DMC_rdd2")
#my_join("metilene_DMC_treat_Col-0_ddm1")
#my_join("metilene_DMC_treat_Col-0_ibm1-1")
#my_join("metilene_DMC_treat_Col-0_rdd2")
my_join("metilene_DMC_Col-0_filtered")
my_join("metilene_DMC_ddm1_filtered")
my_join("metilene_DMC_ibm1-1_filtered")
my_join("metilene_DMC_mock_Col-0_ddm1_filtered")
my_join("metilene_DMC_mock_Col-0_ibm1-1_filtered")
my_join("metilene_DMC_mock_Col-0_rdd2_filtered")
my_join("metilene_DMC_rdd2_filtered")
my_join("metilene_DMC_treat_Col-0_ddm1_filtered")
my_join("metilene_DMC_treat_Col-0_ibm1-1_filtered")
my_join("metilene_DMC_treat_Col-0_rdd2_filtered")
